Repository l-huisman/The-Festival, pull requests merged in 2024-03, with the labels that each got.

#39 Refactor musicService.php and add SongRepository
  app/models/artist.php
  app/repositories/artistRepository.php
  app/repositories/songRepository.php
  app/services/musicService.php
Labels: enhancement

#38 Add QR Generator and Reader functionality
  app/controllers/qrController.php
  app/services/qrGenerator.php
  app/views/qr/reader.php
Labels: enhancement

#40 Refactor code, fix conditional logic, and add delete functionality to CustomController
  app/controllers/customController.php
  app/models/customPage.php
  app/public/index.php
  app/public/js/init.js
  app/repositories/wysiwygRepository.php
  app/services/wysiqyg.php
  app/services/wysiwygService.php
  app/views/404.php
  app/views/custom/index.php
  app/views/home.php
  app/views/home/home.php
  app/views/wysiwyg/index.php
  sql/developmentdb.sql
Labels: enhancement

#41 Refactor code and add custom page functionality
  app/models/venue.php
  app/repositories/venueRepository.php
  app/services/venueService.php
  sql/developmentdb.sql
Labels: enhancement

#42 Fix conditional logic in home.php
  app/views/home.php
Labels: bug, enhancement

#43 Fix conditional logic in home.php
  app/views/home.php
Labels: bug, enhancement

#31 Feature/historic page
  app/controllers/historicController.php
  app/models/historic.php
  app/models/tour.php
  app/public/img/historicevents/bavokerk.jpg
  app/public/img/historicevents/dehallen.jpeg
  app/public/img/historicevents/grotemarkt.jpg
  app/public/img/historicevents/jopenkerk.jpg
  app/public/img/historicevents/proveniershof.jpg
  app/public/styles/historic.css
  app/repositories/historicRepository.php
  app/repositories/tourRepository.php
  app/router/dynamicRouter.php
  app/router/router.php
  app/services/historicService.php
  app/services/tourService.php
  app/views/historic/historicDetail.php
  app/views/historic/historicDetail/historicDetail.php
  app/views/historic/historicOverview.php
  app/views/home.php
Labels: enhancement

#52 resetPasswordRepository error resolved
  app/repositories/resetPasswordRepository.php
Labels: enhancement, fix

#55 Refactor adminController.php and related files, update artist and venue functionality
  app/composer.json
  app/controllers/adminController.php
  app/models/artist.php
  app/models/event.php
  app/repositories/eventRepository.php
  app/repositories/venueRepository.php
  app/router/dynamicRouter.php
  app/services/musicService.php
  app/services/qrGenerator.php
  app/vendor/composer/installed.php
  app/views/admin/artist.php
  app/views/admin/event.php
  app/views/admin/venue.php
  app/views/elements/header.php
  sql/developmentdb.sql
Labels: enhancement

#54 opzet sendTicketService
  app/controllers/sendTicketController.php
  app/services/sendTicketService.php
  app/views/ticket/ticket.php
Labels: enhancement

#58 Add event method to MusicController for buying event tickets
  app/controllers/musicController.php
  app/controllers/shoppingcartController.php
  app/models/artist.php
  app/models/event.php
  app/public/js/player.js
  app/repositories/eventRepository.php
  app/services/musicService.php
  app/views/admin/event.php
  app/views/elements/header.php
  app/views/music/artist.php
  app/views/music/music.php
Labels: enhancement

#59 Update developmentdb(new).sql
  sql/developmentdb(new).sql
Labels: fix
